# Hermetic protocol detection tests. All serial replies are local fixtures.
$ErrorActionPreference = 'Stop'
$tokens = $null
$parseErrors = $null
$firmwarePath = Join-Path (Split-Path $PSScriptRoot -Parent) 'firmware.cmd'
$firmwareAst = [System.Management.Automation.Language.Parser]::ParseFile(
    $firmwarePath, [ref]$tokens, [ref]$parseErrors)
if ($parseErrors.Count) { throw "firmware.cmd parse failed: $parseErrors" }

function Assert-True {
    param([bool]$Condition, [string]$Message)
    if (-not $Condition) { throw $Message }
}
function Assert-Equal {
    param($Expected, $Actual, [string]$Message)
    if ($Expected -ne $Actual) { throw "$Message Expected '$Expected', got '$Actual'." }
}
function Assert-Throws {
    param([scriptblock]$Action, [string]$Message)
    $thrown = $false
    try { $null = & $Action } catch { $thrown = $true }
    Assert-True $thrown $Message
}
foreach ($functionName in @(
    'Remove-Ansi', 'Strip-Prefix', 'Test-IsLogLine', 'Get-VersionTokenFromText',
    'Get-UsableSerialResponse', 'Read-ProtobufVarint', 'ConvertFrom-ProtobufMessage',
    'Get-MeshtasticIdentityFromPayload', 'Invoke-MeshtasticInfoProbe',
    'Read-QuickSerialResponse', 'Get-MeshCoreTextInfoProbe',
    'Get-QuickFirmwareNodeInfo', 'Get-UsbNodeInfo', 'Invoke-MeshCoreBinaryCommand',
    'Get-MeshCoreCompanionInfo', 'Get-FirmwareProbeOrder'
)) {
    $definition = $firmwareAst.Find({ param($node)
        $node -is [System.Management.Automation.Language.FunctionDefinitionAst] -and
        $node.Name -eq $functionName
    }, $true)
    if ($null -eq $definition) { throw "Missing function under test: $functionName" }
    Invoke-Expression $definition.Extent.Text
}
$productionProbeOrder = ${function:Get-FirmwareProbeOrder}

function Convert-HexBytes {
    param([string]$Hex)
    return ,([byte[]]@($Hex.Trim() -split '\s+' | ForEach-Object { [Convert]::ToByte($_, 16) }))
}
function New-MeshtasticFrame {
    param([byte[]]$Payload)
    return ,([byte[]](@(0x94, 0xc3, ($Payload.Length -shr 8), ($Payload.Length -band 0xff)) + $Payload))
}

# These payload bytes were serialized by the installed official Meshtastic
# SDK, not generated by the decoder being tested. my_info includes a uint32
# node number and a current pio_env; metadata carries version and model 88.
[byte[]]$myInfoPayload = Convert-HexBytes '1a 1c 08 f8 ac d1 91 01 6a 14 73 65 65 65 64 5f 78 69 61 6f 5f 6e 72 66 35 32 5f 6b 69 74'
[byte[]]$metadataPayload = Convert-HexBytes '6a 10 0a 0c 32 2e 37 2e 34 2e 61 62 63 31 32 33 48 58'
$identity = Get-MeshtasticIdentityFromPayload -Payload $myInfoPayload
Assert-Equal 'seeed_xiao_nrf52_kit' $identity.Board 'MT my_info pio_env was decoded incorrectly.'
Assert-Equal ([uint64]0x12345678) $identity.NodeNumber 'MT uint32 node number was decoded incorrectly.'
$identity = Get-MeshtasticIdentityFromPayload -Payload $metadataPayload
Assert-Equal '2.7.4.abc123' $identity.Version 'MT metadata version was decoded incorrectly.'
Assert-Equal 88 $identity.HardwareModel 'MT metadata model was decoded incorrectly.'

# A valid future unknown field must not prevent decoding known identity.
[byte[]]$futureFields = Convert-HexBytes 'a0 06 96 01 a9 06 01 02 03 04 05 06 07 08 b5 06 09 0a 0b 0c'
$identity = Get-MeshtasticIdentityFromPayload -Payload ([byte[]]($futureFields + $myInfoPayload))
Assert-Equal 'seeed_xiao_nrf52_kit' $identity.Board 'Unknown protobuf fields hid a valid MT identity.'

$offset = 0
$value = Read-ProtobufVarint -Bytes (Convert-HexBytes 'ac 9e 04') -Offset ([ref]$offset)
Assert-Equal ([uint64]69420) $value 'MT nodeless config ID varint decoded incorrectly.'
Assert-Equal 3 $offset 'Varint decoder did not advance the cursor.'
foreach ($hex in @('00', '80', '0a 80', '0a 03 41', '09 01 02', '0d 01 02', '0e 01',
    '08 80 80 80 80 80 80 80 80 80 02')) {
    Assert-Throws { ConvertFrom-ProtobufMessage -Bytes (Convert-HexBytes $hex) } `
        "Malformed protobuf '$hex' was accepted."
}
foreach ($hex in @('1a 00', '6a 00', '30 01', '0a 03 4d 54 21')) {
    Assert-True ($null -eq (Get-MeshtasticIdentityFromPayload -Payload (Convert-HexBytes $hex))) `
        "Non-identity protobuf '$hex' identified a firmware."
}

function New-ProbeSerialFixture {
    param([ValidateSet('Meshtastic', 'MeshCore', 'Text', 'Silent')][string]$Protocol,
        [byte[]]$Reply = @(), [int]$ChunkSize = 3)
    $port = [pscustomobject]@{
        IsOpen = $true
        Protocol = $Protocol
        Reply = $Reply
        ChunkSize = $ChunkSize
        Incoming = (New-Object 'System.Collections.Generic.List[byte]')
        Writes = (New-Object 'System.Collections.Generic.List[object]')
        TextInput = ''
        SuppressVersion = $false
        Closed = 0
        Disposed = 0
    }
    $port | Add-Member ScriptProperty BytesToRead { return $this.Incoming.Count }
    $port | Add-Member ScriptMethod DiscardInBuffer { $this.Incoming.Clear() }
    $port | Add-Member ScriptMethod Write {
        param([byte[]]$Bytes, [int]$Offset, [int]$Count)
        $slice = New-Object byte[] $Count
        [Array]::Copy($Bytes, $Offset, $slice, 0, $Count)
        $this.Writes.Add($slice)
        if ($this.Protocol -eq 'Meshtastic' -and $Count -ge 8 -and $slice[0] -eq 0x94 -and
            $slice[1] -eq 0xc3 -and $slice[4] -eq 0x18) {
            $this.Incoming.AddRange([byte[]]$this.Reply)
        }
        if ($this.Protocol -eq 'MeshCore' -and $Count -eq 5 -and $slice[0] -eq 0x3c -and $slice[3] -eq 0x16) {
            $this.Incoming.AddRange([byte[]]$this.Reply)
        }
    }
    $port | Add-Member ScriptMethod Read {
        param([byte[]]$Buffer, [int]$Offset, [int]$Count)
        $read = [Math]::Min([Math]::Min($Count, $this.ChunkSize), $this.Incoming.Count)
        for ($index = 0; $index -lt $read; $index++) { $Buffer[$Offset + $index] = $this.Incoming[$index] }
        if ($read) { $this.Incoming.RemoveRange(0, $read) }
        return $read
    }
    $port | Add-Member ScriptMethod WriteLine {
        param([string]$Text)
        $this.Writes.Add($Text)
        if ($this.Protocol -ne 'Text') { return }
        # A CommonCLI record requires CR. Simulate leftover binary bytes before
        # the first query so detection has to clear the parser first.
        $this.TextInput += $Text + "`r"
        foreach ($record in @($this.TextInput -split "`r")) {
            if ($record -eq 'board') { $this.Incoming.AddRange([Text.Encoding]::ASCII.GetBytes("board`r`n-> RAK4631`r`n")) }
            elseif (($record -eq 'ver' -or $record -eq 'version') -and -not $this.SuppressVersion) {
                $this.Incoming.AddRange([Text.Encoding]::ASCII.GetBytes("$record`r`n-> v1.18.0.1`r`n"))
            }
            elseif ($record -eq 'get name') { $this.Incoming.AddRange([Text.Encoding]::ASCII.GetBytes("get name`r`n-> fixture repeater`r`n")) }
        }
        $this.TextInput = ''
    }
    $port | Add-Member ScriptMethod ReadExisting {
        $read = [Math]::Min($this.ChunkSize, $this.Incoming.Count)
        [byte[]]$bytes = @($this.Incoming.GetRange(0, $read))
        if ($read) { $this.Incoming.RemoveRange(0, $read) }
        return [Text.Encoding]::ASCII.GetString($bytes)
    }
    $port | Add-Member ScriptMethod Close { $this.Closed++; $this.IsOpen = $false }
    $port | Add-Member ScriptMethod Dispose { $this.Disposed++; $this.IsOpen = $false }
    return $port
}

# Noise and an unrelated frame precede the two actual replies. Each read
# returns only three bytes, splitting both framing headers and protobuf data.
[byte[]]$replies = ([Text.Encoding]::ASCII.GetBytes("INFO: MT firmware boot`r`n")) +
    # A plausible but incomplete noise frame must not hide a later real frame.
    [byte[]]@(0x94, 0xc3, 0x01, 0x00, 0x00) +
    (New-MeshtasticFrame (Convert-HexBytes '30 01')) +
    (New-MeshtasticFrame $myInfoPayload) + (New-MeshtasticFrame $metadataPayload)
$port = New-ProbeSerialFixture -Protocol Meshtastic -Reply $replies
$identity = Invoke-MeshtasticInfoProbe -SerialPort $port -TotalMs 750
Assert-True ($null -ne $identity) 'Fragmented MT identity reply was missed.'
Assert-Equal 'seeed_xiao_nrf52_kit' $identity.Board 'MT stream lost the board field.'
Assert-Equal '2.7.4.abc123' $identity.Version 'MT stream lost the metadata version.'
$disconnectWrites = @($port.Writes | Where-Object {
    $_ -is [byte[]] -and $_.Length -eq 6 -and $_[0] -eq 0x94 -and $_[4] -eq 0x20 -and $_[5] -eq 1
})
Assert-Equal 1 $disconnectWrites.Count 'Confirmed MT probe did not end its protocol session.'
Assert-Equal 3 $port.Writes.Count 'MT identification sent commands beyond wake, config query, and disconnect.'

$port = New-ProbeSerialFixture -Protocol Meshtastic -Reply (New-MeshtasticFrame (Convert-HexBytes '1a 00'))
$identity = Invoke-MeshtasticInfoProbe -SerialPort $port -TotalMs 35
Assert-True ($null -eq $identity) 'Empty MT my_info caused false identification.'
$disconnectWrites = @($port.Writes | Where-Object { $_ -is [byte[]] -and $_.Length -eq 6 -and $_[4] -eq 0x20 })
Assert-Equal 0 $disconnectWrites.Count 'Unconfirmed port received an MT disconnect command.'

[byte[]]$mcInfo = New-Object byte[] 82
$mcInfo[0] = 0x0d
$mcInfo[1] = 14
[Array]::Copy([Text.Encoding]::ASCII.GetBytes('RAK4631'), 0, $mcInfo, 20, 7)
[Array]::Copy([Text.Encoding]::ASCII.GetBytes('v1.18.0.1'), 0, $mcInfo, 60, 9)
[byte[]]$mcReply = ([Text.Encoding]::ASCII.GetBytes("INFO: MeshCore`r`n")) +
    [byte[]]@(0x3e, 0x00, 0x02, 0x01, 0x3e, 0x02, 0x00, 0x83, 0x01) +
    [byte[]]@(0x3e, $mcInfo.Length, 0) + $mcInfo
$port = New-ProbeSerialFixture -Protocol MeshCore -Reply $mcReply -ChunkSize 32
$identity = Get-MeshCoreCompanionInfo -SerialPort $port -TotalMs 250
Assert-Equal 'RAK4631' $identity.Board 'MC companion board reply was not decoded.'
Assert-Equal 'v1.18.0.1' $identity.Version 'MC companion version reply was not decoded.'

$port = New-ProbeSerialFixture -Protocol Text -ChunkSize 256
$port.TextInput = 'binary-junk'
$identity = Get-MeshCoreTextInfoProbe -SerialPort $port -TotalMs 200
Assert-True ($null -ne $identity) 'CommonCLI text probe failed after binary parser pollution.'
Assert-Equal 'RAK4631' $identity.Board 'CommonCLI board query was not recognized.'
Assert-Equal 'v1.18.0.1' $identity.Version 'CommonCLI version query was not recognized.'
foreach ($command in $port.Writes) {
    Assert-True ($command -in @('', 'board', 'version', 'ver')) `
        'CommonCLI identification sent a command outside its read-only queries.'
}
$port = New-ProbeSerialFixture -Protocol Text -ChunkSize 256
$port.SuppressVersion = $true
$identity = Get-MeshCoreTextInfoProbe -SerialPort $port -TotalMs 75
Assert-True ($null -eq $identity) 'An unconfirmed plain text board string alone identified MeshCore.'

# Descriptors and remembered detection choose the query order, never skip the
# actual handshake. Cache keys follow the physical serial, not a recycled COM.
$script:FirmwareProtocolHints = @{ 'remembered-mt' = 'Meshtastic'; 'remembered-mc' = 'MeshCore' }
$order = @(& $productionProbeOrder -UsbIdentity ([pscustomobject]@{
    SerialNumber = 'REMEMBERED-MT'; BusReportedDescription = ''
}))
Assert-Equal 'Meshtastic' $order[0] 'Last successful detection did not choose MT first.'
Assert-Equal 2 $order.Count 'Protocol hint removed the alternative handshake.'
$order = @(& $productionProbeOrder -UsbIdentity ([pscustomobject]@{
    SerialNumber = 'remembered-mt'; BusReportedDescription = 'MeshCore Full Companion'
}))
Assert-Equal 'MeshCore' $order[0] 'Fresh MC descriptor did not choose MC first.'
$order = @(& $productionProbeOrder -UsbIdentity ([pscustomobject]@{
    SerialNumber = 'a-different-radio'; BusReportedDescription = ''
}))
Assert-Equal 2 $order.Count 'An unknown USB serial was restricted to one protocol.'

# Exercise the inventory path with no real USB or serial handles. Firmware
# identity comes only from a reply, while a descriptor chooses the first query.
$script:fixtureProtocol = 'Meshtastic'
$script:fixtureIdentity = [pscustomobject]@{
    ParentInstanceId = 'USB\VID_239A&PID_8029\fixture'
    BusReportedDescription = 'MeshCore Full Companion'
    InterfaceNumber = '00'
    DfuTest = $false
}
$script:fixtureOpenCalls = 0
$script:fixtureQueryCalls = (New-Object 'System.Collections.Generic.List[string]')
$script:fixturePort = $null
$script:fixtureBusy = $false
$script:fixtureCloseThrows = $false
function Get-UsbComPortIdentity { param($ComPort) return $script:fixtureIdentity }
function Test-UsbIdentityIsNrf52Dfu {
    param([Parameter(Mandatory)]$Identity)
    return $Identity.DfuTest
}
function Get-FirmwareProbeOrder { param($UsbIdentity) return @('MeshCore', 'Meshtastic') }
function Open-SerialPort {
    param($ComPort, $Baud, $ReadTimeoutMs, $WriteTimeoutMs, $Dtr, $Rts)
    $script:fixtureOpenCalls++
    $script:fixtureDtr = $Dtr
    $script:fixtureRts = $Rts
    if ($script:fixtureBusy) { throw [UnauthorizedAccessException]::new('Access to COM_TEST is denied.') }
    $script:fixturePort = New-ProbeSerialFixture -Protocol Silent
    $script:fixturePort | Add-Member -Force ScriptMethod Close {
        $this.Closed++
        $this.IsOpen = $false
        if ($script:fixtureCloseThrows) { throw [IO.IOException]::new('USB was unplugged during cleanup.') }
    }
    return $script:fixturePort
}
function Get-MeshCoreCompanionInfo {
    param($SerialPort, $TotalMs)
    $script:fixtureQueryCalls.Add('MeshCore')
    if ($script:fixtureProtocol -eq 'MeshCore') {
        return [pscustomobject]@{ Board = 'RAK4631'; Version = 'v1.18.0.1'; Protocol = 14 }
    }
    return $null
}
function Get-MeshCoreTextInfoProbe {
    param($SerialPort, $TotalMs)
    $script:fixtureQueryCalls.Add('CommonCLI')
    if ($script:fixtureProtocol -eq 'CommonCLI') {
        return [pscustomobject]@{ Board = 'RAK4631'; Version = 'v1.18.0.1'; Name = 'repeater' }
    }
    return $null
}
function Invoke-MeshtasticInfoProbe {
    param($SerialPort, $TotalMs)
    $script:fixtureQueryCalls.Add('Meshtastic')
    if ($script:fixtureProtocol -eq 'Meshtastic') {
        return [pscustomobject]@{
            Board = 'seeed_xiao_nrf52_kit'; Version = '2.7.4.abc123'; HardwareModel = 88
            NodeNumber = [uint64]0x12345678; Name = ''
        }
    }
    return $null
}
function Get-MeshtasticHardwareName { param($Model) return 'XIAO_NRF52_KIT' }

$result = Get-QuickFirmwareNodeInfo -ComPort COM_TEST -UsbIdentity $script:fixtureIdentity -TotalMs 1
Assert-True $result.Success 'Stale MC descriptor prevented detecting running MT firmware.'
Assert-Equal 'Meshtastic' $result.Project 'Descriptor was mistaken for positive protocol identification.'
Assert-Equal '2.7.4.abc123' $result.FWVersion 'Quick detector dropped MT metadata.'
Assert-Equal 1 $script:fixtureOpenCalls 'Quick detector reopened serial between protocols.'
Assert-True (-not $script:fixturePort.IsOpen) 'Successful detection left the serial port locked.'
Assert-True ($script:fixturePort.Closed + $script:fixturePort.Disposed -gt 0) 'Quick detector did not clean up its serial port.'
Assert-True ($script:fixtureDtr -and $script:fixtureRts) 'nRF52 CDC lost its session signaling.'

$opensBeforeNoIdentity = $script:fixtureOpenCalls
$result = Get-QuickFirmwareNodeInfo -ComPort COM_TEST -UsbIdentity $null -TotalMs 1
Assert-True $result.Success 'Missing USB descriptor prevented a valid protocol handshake.'
Assert-Equal ($opensBeforeNoIdentity + 1) $script:fixtureOpenCalls 'Missing USB identity skipped serial identification.'
Assert-True ($script:fixtureDtr -and $script:fixtureRts) 'Missing USB descriptor changed CDC session signaling.'

$script:fixtureCloseThrows = $true
$result = Get-QuickFirmwareNodeInfo -ComPort COM_TEST -UsbIdentity $script:fixtureIdentity -TotalMs 1
Assert-True $result.Success 'USB cleanup failure discarded a completed protocol identification.'
Assert-Equal 1 $script:fixturePort.Disposed 'USB close failure prevented disposal of the handle.'
$script:fixtureCloseThrows = $false

$script:fixtureProtocol = 'MeshCore'
$script:fixtureIdentity = [pscustomobject]@{
    ParentInstanceId = 'USB\VID_303A&PID_1001\fixture-v4'
    BusReportedDescription = 'USB JTAG/serial debug unit'
    InterfaceNumber = '00'
    DfuTest = $false
}
$result = Get-QuickFirmwareNodeInfo -ComPort COM_TEST -UsbIdentity $script:fixtureIdentity -TotalMs 1
Assert-True $result.Success 'Native ESP32 MC fixture was not identified.'
Assert-True (-not $script:fixtureDtr -and -not $script:fixtureRts) 'Native ESP32 inventory asserted reset/download control lines.'

$script:fixtureProtocol = 'Silent'
$result = Get-QuickFirmwareNodeInfo -ComPort COM_TEST -UsbIdentity $script:fixtureIdentity -TotalMs 1
Assert-True (-not $result.Success) 'Silent device was identified from a USB descriptor.'
Assert-Equal 'unknown' $result.ProbeState 'Silence was treated as a positive firmware identity.'
Assert-True (-not $script:fixturePort.IsOpen) 'Unknown detection left the serial port locked.'

$script:fixtureIdentity.DfuTest = $true
$opensBeforeDfu = $script:fixtureOpenCalls
$result = Get-QuickFirmwareNodeInfo -ComPort COM_TEST -UsbIdentity $script:fixtureIdentity -TotalMs 1
Assert-Equal 'dfu' $result.ProbeState 'Known DFU identity was not skipped.'
Assert-Equal $opensBeforeDfu $script:fixtureOpenCalls 'Known DFU interface was opened for an application handshake.'
$script:fixtureIdentity.DfuTest = $false
$script:fixtureBusy = $true
$result = Get-QuickFirmwareNodeInfo -ComPort COM_TEST -UsbIdentity $script:fixtureIdentity -TotalMs 1
Assert-Equal 'busy' $result.ProbeState 'Access-denied serial error did not report a busy port.'
$script:fixtureBusy = $false

# Slower compatibility detection is only for a genuinely unknown device.
# Retrying a busy handle or bootloader does not provide additional evidence.
$script:fakeQuickState = 'busy'
$script:legacyCalls = 0
function Get-QuickFirmwareNodeInfo {
    param($ComPort, $UsbIdentity, $TotalMs)
    return [pscustomobject]@{ Success = $false; ProbeState = $script:fakeQuickState }
}
function getMeshCore {
    param($ComPort)
    $script:legacyCalls++
    return [pscustomobject]@{ Success = $false }
}
function getMeshtasticNodeInfo {
    param($ComPort)
    $script:legacyCalls++
    return [pscustomobject]@{
        Success = $true; ComPort = $ComPort; Project = 'Meshtastic'; HWName = 'legacy'
        HWNameShort = 'legacy'; FWVersion = '2.6.0'; ExtraInfo = ''
    }
}
foreach ($state in @('busy', 'dfu', 'unavailable')) {
    $script:fakeQuickState = $state
    $result = Get-UsbNodeInfo -ComPort COM_TEST -UsbIdentity $script:fixtureIdentity
    Assert-Equal 0 $script:legacyCalls "The $state result triggered a long compatibility probe."
}
$script:fakeQuickState = 'unknown'
$result = Get-UsbNodeInfo -ComPort COM_TEST -UsbIdentity $script:fixtureIdentity -QuickOnly
Assert-True (-not $result.Success) 'Initial inventory turned silence into a positive firmware identity.'
Assert-Equal 0 $script:legacyCalls 'Initial quick-only inventory waited for the slow compatibility detector.'
$result = Get-UsbNodeInfo -ComPort COM_TEST -UsbIdentity $script:fixtureIdentity
Assert-True $result.Success 'Unknown quick result did not retain the slower compatibility fallback.'
Assert-Equal 2 $script:legacyCalls 'Fallback did not try both protocols when the first was silent.'

Write-Host 'PASS: MT/MC protocol detection, malformed/noisy framing, DFU/busy handling, and safe serial cleanup.'
